apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: boutique
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`boutique.homelab.local`)
      kind: Rule
      services:
        - name: frontend
          port: 80
  tls: {}
