# Traefik v3 (chart v40) — wartosci pod homelab 16 GB RAM
deployment:
  replicas: 1

service:
  type: LoadBalancer
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.4.200"

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443

ingressRoute:
  dashboard:
    enabled: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 128Mi

logs:
  general:
    level: INFO
